---

language: 'python'
sudo: False

matrix:
  include:
  -   env: 'TOXENV=py34'
      python: '3.4'
  -   env: 'TOXENV=py35'
      python: '3.5'
  -   env: 'TOXENV=py36'
      python: '3.6'
install:
  - 'pip install coveralls tox-travis'
script:
  - 'tox -e "${TOXENV}"'
after_success:
  - 'coveralls'
