---

# Pyup configuration

branch: 'develop'
requirements:
  - 'requirements.txt'
  - '%7B%7B%20cookiecutter.project_slug%20%7D%7D/requirements.txt'
  - '%7B%7B%20cookiecutter.project_slug%20%7D%7D/setup.cfg'
