---

# Travis file for cookiecutter ansible role template

language: python

install:
  # Install python pytest plugin to cookiecutter template testing
  - pip install -r requirements.txt

script:
  # Run tests
  - tox
